
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
        - script: "ng build"
        displayName: 'Building Stage'
  
  - stage: Test
    jobs:
      - job: TestJob
        steps:
          - script: "ng test"
            displayName: 'Testing Stage'
        
          
            
               