# Node.js
# Build a general Node.js project with npm and run tests in headless mode.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Install necessary dependencies for headless Chrome with sudo
- script: |
    sudo apt-get update
    sudo apt-get install -y libnss3 libxss1 libappindicator1 libindicator7 libfontconfig1
  displayName: 'Install dependencies for headless Chrome'

# Install project dependencies and build the project
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Run tests with headless Chrome
- script: |
    npm test
  displayName: 'Run Tests in Headless Chrome'
  env:
    CHROME_BIN: "/usr/bin/google-chrome"
