trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Echo Source Folder Path
- script: |
    echo "Source Folder Path: $(Build.SourcesDirectory)"
    ls $(Build.SourcesDirectory)
  displayName: 'Show Source Folder Path'
