# Node.js
# Build and test a Node.js project using npm, leveraging the provided scripts in package.json.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Install dependencies and build the project using the "build" script in package.json
- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build the project'

# Run tests using the "test" script in package.json
- script: npm run test
  displayName: 'Run Tests'
