- task: AngularCLI@1
  inputs:
    command: 'build'
    DisableAnalytics: false

- task: AngularCLI@1
  inputs:
    command: 'test'
    DisableAnalytics: false

- task: AngularCLI@1
  inputs:
    command: 'custom'
    verbose: true
    DisableAnalytics: false