trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stageA
    displayName: "This is stage A"
    jobs:
      - job: jobA

  - stage: stageB
    displayName: "This is stage B"
    jobs:
      -  job: jobB

