trigger:
  branches:
    include:
      - main  # Change this to your working branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Install Node.js and Angular CLI
- task: UseNode@1
  inputs:
    version: '18.x'

# Install Angular Project Dependencies
- script: |
    cd frontend
    npm install
    npm run build 
  displayName: 'Build Angular Frontend'

# Deploy to GitHub Pages
- task: Checkout@1
  inputs:
    repository: https://github.com/Estimation-2/repo2.git
    clean: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git add azure-pipelines.yml
      git commit -m "Automated Deployment"
      git push origin main