trigger:
  branches:
    include:
      - main  # Change this to your working branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Install Node.js and Angular CLI
- task: UseNode@1
  inputs:
    version: '18.x'

# Install Angular Project Dependencies
- script: |
    cd frontend
    npm install
    npm run build 
  displayName: 'Build Angular Frontend'

# Deploy to GitHub Pages
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.name "Estimation-2"
      git config --global user.email "veeranki.supriya@mphasis.com"
      npx angular-cli-ghpages --dir=dist/estimation-app --no-silent
