pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install npm dependencies'

- task: Npm@1
  inputs:
    command: 'run'
    arguments: 'test -- --browsers=ChromeHeadless'
  displayName: 'Run Tests'
