trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Install Node.js and Build Angular Project
- task: UseNode@1
  inputs:
    version: '18.x'

- script: |
    cd frontend
    npm install
    npm run build 
  displayName: 'Build Angular Frontend'

# Deploy to GitHub Using HTTPS (With Token)
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Configure GitHub User
      git config --global user.name "Estimation-2"
      git config --global user.email "veeranki.supriya@mphasis.com"

     