
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          
        - task: Npm@0
        displayName: npm install
    
  - stage: Test
    jobs:
      - job: TestJob
        steps:
          -  script: run test
            
               