name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Start with only one version for simplicity

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6  # Upgraded setup-node action
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --prod

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6  # Upgraded setup-node action
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Install necessary dependencies for testing
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget curl unzip \
          libx11-xcb1 libfontconfig libnss3 libasound2 libgbm1 \
          libxcomposite1 libxrandr2 libgdk-pixbuf2.0-0 libxtst6 \
          libgtk-3-0
    - name: Print installed packages
      run: dpkg -l  # Debugging step to print installed packages
    - name: Run tests with headless Chrome
      run: npm test -- --watch=false --browsers=ChromeHeadless
      env:
        DISPLAY: :99  # Set display for headless testing
